FROM node:20-bullseye

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Puerto interno (debe coincidir con VITE_APP_PORT del .env)
EXPOSE 3004

CMD ["npm", "run", "dev"]
