import { useState } from 'react'
import { BookOpen, ChevronDown, FileDown, FileUp, Plus, ShieldCheck, UserCog, X } from 'lucide-react'
import { DashboardLayout } from '../../../shared/layout/DashboardLayout'
import type { Section } from '../../../shared/components/Sidebar'
const initialUsers = [
  { name: 'María González', email: 'maria.gonzalez@universidad.cl', role: 'Administrador', scope: 'Institucional', status: 'Activo' },
  { name: 'Carlos Ramírez', email: 'carlos.ramirez@universidad.cl', role: 'Analista', scope: 'Facultad de Ingeniería', status: 'Activo' },
  { name: 'Ana Soto', email: 'ana.soto@universidad.cl', role: 'Director de carrera', scope: 'Ing. Civil Informática', status: 'Activo' },
]

export default function DashboardAdmin() {
  const [section, setSection] = useState<Section>('Dashboard')
  const [open, setOpen] = useState(true)
  const [period, setPeriod] = useState('2026 - Semestre 1')
  const [users, setUsers] = useState(initialUsers)
  const [notice, setNotice] = useState('')
  const [modal, setModal] = useState<'period' | 'user' | null>(null)
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  const go = (label: Section) => { setSection(label) }

  return <DashboardLayout section={section} open={open} onToggle={() => setOpen(!open)} onNavigate={go}>
    <div className="mx-auto max-w-[1440px] p-5 sm:p-8 lg:p-10">
      <header className="mb-8 flex flex-col gap-5 border-b border-[#D9E5F0] pb-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-[#556B7B]">Consola de administración</p><h1 className="text-balance text-3xl font-bold tracking-tight text-[#003366] sm:text-4xl">{section}</h1><p className="mt-2 text-sm text-[#556B7B]">Plataforma para Generar Reporterías de Indicadores de Progresión Académica y Curricular</p></div><div className="flex flex-wrap items-center gap-2"><label className="flex items-center rounded-lg border border-[#D9E5F0] bg-[#FFFFFF] px-3 shadow-sm"><span className="mr-2 text-xs text-[#556B7B]">Período:</span><select value={period} onChange={e => setPeriod(e.target.value)} className="bg-transparent py-2 text-sm font-semibold text-[#003366] outline-none" aria-label="Seleccionar período"><option>2026 - Semestre 1</option><option>2025 - Semestre 2</option><option>2025 - Semestre 1</option></select><ChevronDown className="ml-2 size-3.5 text-[#556B7B]" /></label></div></header>
      {section === 'Dashboard' && <Overview onNavigate={go} />}
      {section === 'Períodos académicos' && <Periods period={period} setPeriod={setPeriod} onNew={() => setModal('period')} flash={flash} />}
      {section === 'Cargas de datos' && <DataLoads flash={flash} />}
      {section === 'Usuarios y permisos' && <UsersPanel users={users} setUsers={setUsers} onNew={() => setModal('user')} flash={flash} />}
    </div>
    {modal && <Modal type={modal} close={() => setModal(null)} flash={flash} />}{notice && <div role="status" className="fixed bottom-5 right-5 rounded-lg bg-[#003366] px-4 py-3 text-sm font-medium text-white shadow-xl">{notice}</div>}
  </DashboardLayout>
}

function Overview({ onNavigate }: { onNavigate: (section: Section) => void }) { return <div className="flex flex-col gap-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Períodos configurados" value="8" note="2 activos actualmente" /><Metric title="Última carga de datos" value="98%" note="Validación completada" positive /><Metric title="Usuarios activos" value="24" note="5 roles configurados" /><Metric title="Reportes generados" value="146" note="↑ 18% vs. período anterior" positive /></div><div className="grid gap-8 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border border-border bg-card p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-muted-foreground">Estado del sistema</p><h2 className="mt-1 text-xl font-bold">Centro de operaciones</h2></div><ShieldCheck className="size-5 text-progress-efficient" /></div><div className="mt-6 flex flex-col gap-3"><Status label="Período 2026 - Semestre 1" detail="Publicado y visible para reportes" tone="success" /><Status label="Carga de matrícula" detail="Validada hace 18 minutos" tone="success" /><Status label="Carga de calificaciones" detail="Pendiente de actualización" tone="warning" /></div><button onClick={() => onNavigate('Cargas de datos')} className="mt-6 text-sm font-semibold text-foreground underline decoration-primary underline-offset-4">Revisar cargas de datos</button></section><section className="rounded-xl border border-border bg-card p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.15em] text-muted-foreground">Acciones rápidas</p><h2 className="mt-1 text-xl font-bold">Administrar plataforma</h2><div className="mt-6 flex flex-col gap-3"><Quick icon={BookOpen} text="Crear período académico" onClick={() => onNavigate('Períodos académicos')} /><Quick icon={FileUp} text="Cargar archivo de datos" onClick={() => onNavigate('Cargas de datos')} /><Quick icon={UserCog} text="Gestionar usuarios y roles" onClick={() => onNavigate('Usuarios y permisos')} /></div></section></div></div> }
function Metric({ title, value, note, positive }: { title: string; value: string; note: string; positive?: boolean }) { return <article className="rounded-xl border border-[#b2b2b2] bg-[#ffffff] p-5 shadow-sm"><p className="text-sm font-semibold text-[#878787]">{title}</p><p className="mt-5 text-3xl font-bold tracking-tight text-[#1d1d1b]">{value}</p><p className={`mt-3 text-xs font-medium ${positive ? 'text-[#00693e]' : 'text-[#878787]'}`}>{positive && '↑ '}{note}</p></article> }
function Status({ label, detail, tone }: { label: string; detail: string; tone: 'success' | 'warning' }) { return <div className="flex items-center justify-between gap-4 rounded-lg border border-[#b2b2b2] p-4"><div><p className="text-sm font-semibold text-[#1d1d1b]">{label}</p><p className="mt-1 text-xs text-[#878787]">{detail}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone === 'success' ? 'bg-[#ffc82e] text-[#1d1d1b]' : 'bg-[#b2b2b2]/30 text-[#1d1d1b]'}`}>{tone === 'success' ? 'Listo' : 'Pendiente'}</span></div> }
function Quick({ icon: Icon, text, onClick }: { icon: typeof BookOpen; text: string; onClick: () => void }) { return <button onClick={onClick} className="flex items-center gap-3 rounded-lg border border-[#b2b2b2] p-4 text-left text-sm font-semibold text-[#1d1d1b] transition-colors hover:bg-[#f7f7f7]"><Icon className="size-5 text-[#00693e]" />{text}<ChevronDown className="ml-auto size-4 -rotate-90 text-[#878787]" /></button> }
function Periods({ period, setPeriod, onNew, flash }: { period: string; setPeriod: (value: string) => void; onNew: () => void; flash: (message: string) => void }) { const rows = ['2026 - Semestre 1', '2025 - Semestre 2', '2025 - Semestre 1', '2024 - Semestre 2']; return <Panel title="Períodos académicos" eyebrow="Configuración temporal" action="Nuevo período" onAction={onNew}><p className="mb-5 text-sm text-muted-foreground">Define los períodos disponibles para la carga, publicación y generación de reporterías.</p><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><th className="pb-3">Período</th><th className="pb-3">Estado</th><th className="pb-3">Datos disponibles</th><th className="pb-3 text-right">Acción</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row} className="border-b border-border/70"><td className="py-4 font-semibold">{row}</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${index === 0 ? 'bg-progress-efficient/15 text-progress-efficient' : 'bg-muted text-muted-foreground'}`}>{index === 0 ? 'Activo' : 'Cerrado'}</span></td><td className="py-4 text-muted-foreground">{index < 2 ? 'Matrícula · Notas · Retención' : 'Matrícula · Notas'}</td><td className="py-4 text-right"><button onClick={() => { setPeriod(row); flash(`Período ${row} seleccionado`) }} className="font-semibold underline underline-offset-4">Seleccionar</button></td></tr>)}</tbody></table></div></Panel> }
function DataLoads({ flash }: { flash: (message: string) => void }) { return <div className="flex flex-col gap-6"><Panel title="Carga de datos" eyebrow="Ingesta y validación"><div className="rounded-lg border border-dashed border-border bg-muted/30 p-6 text-center"><FileUp className="mx-auto size-8 text-primary" /><h3 className="mt-3 font-semibold">Carga única de información académica</h3><p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">Sube un solo archivo CSV con toda la información de matrícula, calificaciones, progresión, retención y titulación.</p><input id="academic-csv" type="file" accept=".csv,text/csv" className="sr-only" onChange={event => event.target.files?.[0] && flash(`Archivo ${event.target.files[0].name} seleccionado`)} /><label htmlFor="academic-csv" className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold"><FileUp className="size-4" /> Seleccionar CSV</label><p className="mt-3 text-xs text-muted-foreground">Formato permitido: CSV · Incluye todos los campos del período seleccionado</p></div></Panel><Panel title="Flujo de publicación" eyebrow="Control de calidad"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex-1 rounded-lg border border-border p-4"><p className="text-sm font-semibold">1. Descargar plantilla</p><p className="mt-1 text-xs text-muted-foreground">Usa la plantilla única para completar todos los registros.</p><button onClick={() => flash('Plantilla CSV descargada')} className="mt-4 flex items-center gap-2 text-xs font-semibold underline"><FileDown className="size-4" /> Descargar plantilla CSV</button></div><div className="flex-1 rounded-lg border border-border p-4"><p className="text-sm font-semibold">2. Validar información</p><p className="mt-1 text-xs text-muted-foreground">Revisa errores de formato, duplicados y campos obligatorios.</p><button onClick={() => flash('Validación ejecutada: sin errores críticos')} className="mt-4 rounded-lg bg-primary px-3 py-2 text-xs font-semibold">Ejecutar validación</button></div><div className="flex-1 rounded-lg border border-border p-4"><p className="text-sm font-semibold">3. Publicar datos</p><p className="mt-1 text-xs text-muted-foreground">Haz visibles todos los indicadores para los usuarios autorizados.</p><button onClick={() => flash('Datos publicados correctamente')} className="mt-4 rounded-lg bg-sidebar px-3 py-2 text-xs font-semibold text-sidebar-foreground">Publicar período</button></div></div></Panel></div> }
function UsersPanel({ users, setUsers, onNew, flash }: { users: typeof initialUsers; setUsers: (users: typeof initialUsers) => void; onNew: () => void; flash: (message: string) => void }) { return <Panel title="Usuarios y permisos" eyebrow="Acceso y roles" action="Nuevo usuario" onAction={onNew}><p className="mb-5 text-sm text-muted-foreground">Administra quién puede acceder a la plataforma y qué información puede consultar.</p><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><th className="pb-3">Usuario</th><th className="pb-3">Rol</th><th className="pb-3">Ámbito</th><th className="pb-3">Estado</th><th className="pb-3 text-right">Acciones</th></tr></thead><tbody>{users.map((user, index) => <tr key={user.email} className="border-b border-border/70"><td className="py-4"><p className="font-semibold">{user.name}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td className="py-4">{user.role}</td><td className="py-4 text-muted-foreground">{user.scope}</td><td className="py-4"><span className="rounded-full bg-progress-efficient/15 px-2.5 py-1 text-xs font-semibold text-progress-efficient">{user.status}</span></td><td className="py-4 text-right"><button onClick={() => { const next = [...users]; next[index] = { ...user, status: user.status === 'Activo' ? 'Deshabilitado' : 'Activo' }; setUsers(next); flash('Estado del usuario actualizado') }} className="font-semibold underline underline-offset-4">{user.status === 'Activo' ? 'Deshabilitar' : 'Habilitar'}</button></td></tr>)}</tbody></table></div></Panel> }
function Field({ label, value }: { label: string; value: string }) { return <label className="flex flex-col gap-2 text-sm font-semibold">{label}<input defaultValue={value} className="rounded-lg border border-border bg-background px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-ring" /></label> }
function Panel({ title, eyebrow, action, onAction, children }: { title: string; eyebrow: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="rounded-xl border border-[#b2b2b2] bg-[#ffffff] p-5 shadow-sm sm:p-6"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#878787]">{eyebrow}</p><h2 className="mt-1 text-xl font-bold tracking-tight text-[#1d1d1b]">{title}</h2></div>{action && <button onClick={onAction} className="flex items-center gap-2 rounded-lg bg-[#ffc82e] px-3 py-2 text-sm font-semibold text-[#1d1d1b]"><Plus className="size-4" />{action}</button>}</div>{children}</section> }
function Modal({ type, close, flash }: { type: 'period' | 'user'; close: () => void; flash: (message: string) => void }) { return <div className="fixed inset-0 z-10 flex items-center justify-center bg-foreground/30 p-5"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-xl border border-border bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{type === 'period' ? 'Nuevo período académico' : 'Nuevo usuario'}</h2><button onClick={close} aria-label="Cerrar"><X className="size-5" /></button></div><div className="mt-6 flex flex-col gap-4">{type === 'period' ? <><Field label="Año" value="2027" /><Field label="Nombre del período" value="Semestre 1" /></> : <><Field label="Nombre completo" value="" /><Field label="Correo institucional" value="" /><Field label="Rol" value="Analista" /></>}</div><button onClick={() => { close(); flash(type === 'period' ? 'Período creado correctamente' : 'Invitación enviada al usuario') }} className="mt-6 w-full rounded-lg bg-primary px-4 py-3 text-sm font-semibold">{type === 'period' ? 'Crear período' : 'Enviar invitación'}</button></div></div> }